name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  email_validator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_screenutil: ^5.9.3
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  pinput: ^5.0.0
  responsive_sizer: ^3.3.1
  shimmer: ^3.0.0
  validation_pro: ^1.2.0
  cupertino_icons: ^1.0.2
  transparent_image: ^2.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.7.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  responsive_builder: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
