name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_screenutil: ^5.9.3
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  responsive_sizer: ^3.3.1
  shimmer: ^3.0.0
  validation_pro: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  responsive_builder: ^0.7.0

flutter:
  uses-material-design: true
