List<String> paymentType = [
  "Any",
  "Monthly",
  "Annually",
  "Per Night",
  "Per Week"
];

List<String> propertyType = [
  "Any",
  "Apartment",
  "House",
  "Student Hostel",
  "Hotel",
  "Guest House",
  "Office Space",
  "Shop",
  "Warehouse",
  "Event Space"
];

List<String> amenities = [
  "Air Conditioning",
  "Heating",
  "Balcony",
  "Deck",
  "Patio",
  "Garden",
  "Garage",
  "Parking Space",
  "Security System",
  "Gated Community",
  "Elevator",
  "High-Speed Internet",
  "Cable TV",
  "Wi-Fi",
  "Study room",
  "Library",
  "Cafe",
  "Fireplace",
  "Furnished",
  "Unfurnished",
  "Wheelchair Accessible",
  "Pet-Friendly",
  "Non-Smoking",
  "Utilities Included",
  "Swimming Pool",
  "Washrooms",
  "Bathrooms",
  "Kitchen",
  "Toilet facilities",
  "Bedrooms",
  "Gym",
  "Spa",
  "Sauna",
  "Playground",
  "Tennis Court",
  "Basketball Court",
  "Clubhouse",
  "Laundry Room",
  "In-Unit Washer/Dryer",
  "Shared Laundry Facilities",
  "Storage Space",
  "Walk-In Closet",
  "Dishwasher",
  "Microwave",
  "Refrigerator",
  "Stove/Oven",
  "Conference Room",
  "Meeting Room",
  "Reception Area",
  "Break Room",
  "Kitchenette",
  "On-Site Management",
  "Business Center",
  "Loading Dock",
  "Shipping Area",
  "24/7 Access",
  "Printing Facilities",
  "Copying Facilities",
  "Mail Room",
  "Server Room",
  "Backup Power Supply",
  "CCTV Surveillance",
  "Concierge Service",
  "Cleaning Service",
  "Maintenance Service",
  "Guest Parking",
  "Rooftop Access",
  "Community Events",
  "Public Transport Access",
  "Bike Storage",
  "Recycling Facilities",
  "Electric Vehicle Charging Station",
  "Smart Home Technology",
  "Solar Panels",
  "Green Building Certification",
  "Walking Trails",
  "Scenic View",
  "Waterfront Access",
  "Private Beach",
  "Beach View",
  "Dock Access"
];
