import 'package:get_it/get_it.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:http/http.dart' as http;
import 'package:internet_connection_checker/internet_connection_checker.dart';
import 'package:mobile/src/core/network/network_info.dart';
import 'package:mobile/src/features/auth/data/data_sources/auth_local_data_source.dart';
import 'package:mobile/src/features/auth/data/data_sources/auth_remote_data_source.dart';
import 'package:mobile/src/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:mobile/src/features/auth/domain/domain.dart';
import 'package:mobile/src/features/auth/domain/use_cases/forgot_password_usecase.dart';
import 'package:mobile/src/features/auth/domain/use_cases/get_cached_user_usecase.dart';
import 'package:mobile/src/features/auth/domain/use_cases/resend_otp_usecase.dart';
import 'package:mobile/src/features/auth/domain/use_cases/verify_otp.dart';
import 'package:mobile/src/features/auth/presentation/bloc/bloc/authentication_bloc.dart';
import 'package:mobile/src/core/cubit/app_user/app_user_cubit.dart';
import 'package:mobile/src/features/dashboard/data/data.dart';
import 'package:mobile/src/features/dashboard/domain/domain.dart';
import 'package:mobile/src/features/dashboard/presentation/bloc/conpare_listings_bloc/conpare_listings_bloc.dart';
import 'package:mobile/src/features/dashboard/presentation/bloc/listing_details/listing_details_bloc.dart';
import 'package:mobile/src/features/dashboard/presentation/bloc/listings/dashboard_bloc.dart';
import 'package:mobile/src/features/dashboard/presentation/bloc/location/location_bloc.dart';

part "dp_injection.dart";
